### ISSUE TITLE
Alternative for Linux or anything with sed

### ISSUE THREAD

**Issue by sevmonster** [tactu1/synthetik-crux-fix#1]
A lot of work into this for something that can easily be accomplished with a single `sed` command.
```sh
sed -Ei 's/(idropchange 149=")[[:digit:]\.-]+$/\10.000000/' Save.sav
````
Works for anything with `sed` (Git for Windows, cygwin, msys, mingw, WSL, Busybox, etc.)

If you don't have `sed` but want a more compact solution, an alternative is PowerShell, which comes installed on all Windows machines past Vista.
```PowerShell
$x = 'Save.sav'; (gc $x | % {$_ -replace '(idropchange 149=")[\d\.-]+', '${1}0.000000'}) | sc $x
```
 In general it is wasteful to use more than one file here (cmd + vbs) where only one will suffice.

**Comment by tactu1** [comment]
couple of things
1) I felt like doing it this way
2) As noted, they could also find some way to do it in powershell as well, but that doesn't obviate the point of this project which is just something I wanted to do visual basic because i hadn't done a visual basic project in a while.
3) If you looked over the cmd file, you'll note that it's primary purpose is to combine the actions of get the game started immediately after doing the edit, the most essential purpose a batch file. Editing the save file is completely contained in the vb script.

**Comment by sevmonster** [comment]
Even then, it is still possible to minimize them to one file.
1. Embed WSF into batch file: https://stackoverflow.com/a/9078410
2. Use the `Run` method of `WScript.Shell` for the `steam://` URI, e.g.: `CreateObject("WScript.Shell").Run("steam://rungameid/528230")`

You might consider waiting before launching the game to give Steam Cloud time to sync. Launching the game right as the file is edited *might* cause a popup complaining about unsynced data. I usually get it when quickly relaunching the game after it closes (i.e. crashes) and rarely when editing the save right before a cold launch.
![image](https://user-images.githubusercontent.com/16788697/156930290-10e6c6d4-6a6f-4d39-9614-8e290fcba9df.png)
